debug: false
layout: sidebar # prefer to stacked
style: dark # prefer to light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  stackoverflow: 6357722
  telegram: mcatf
  twitter: TheuCatarino
  youtube: matheus_catarino

topics:
  - name: C++ Programming Language
    web_url: https://isocpp.org
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/cpp/cpp.png
    
  - name: Lua Programming Language
    web_url: https://lua.org
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/lua/lua.png

  - name: Python Programming Language
    web_url: https://www.python.org
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
    
  - name: Qt Framework
    web_url: https://qt.io
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/qt/qt.png
  
  - name: Rust Programming Language
    web_url: https://rust-lang.org
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/rust/rust.png

  - name: Zig Programming Language
    web_url: https://ziglang.org
    image_url: https://raw.githubusercontent.com/github/explore/b28ef5e65d2d582ab36c30e3e2068721e71625e4/topics/zig/zig.png
